### ISSUE TITLE
[Question] rc5 ready?

### ISSUE THREAD

**Issue by rmoscowitz** [ui-router/ng1-to-ng2#12]
Sorry if I'm jumping the gun (I know you haven't updated sample-app-ng1-to-ng2 to rc5 yet). Should I be able to use ng1-to-ng2 with angular2.rc5?

I've upgraded my hybrid app to...
```
"@angular/common": "2.0.0-rc.5",
"@angular/compiler": "2.0.0-rc.5",
"@angular/core": "2.0.0-rc.5",
"@angular/http": "2.0.0-rc.5",
"@angular/platform-browser": "2.0.0-rc.5",
"@angular/platform-browser-dynamic": "2.0.0-rc.5",
"@angular/upgrade": "2.0.0-rc.5",
"ui-router-ng2": "1.0.0-beta.1",
"ui-router-ng1-to-ng2": "1.0.10"
```

I've created an NgModule (almost an exact copy/paste from quickstart-ng2) and exported the UpgradeAdapter with my module... 

`export const upgradeAdapter = new UpgradeAdapter(AppModule);`

In my angular1 code, I've bootstrapped with my exported upgradeAdapter:

```
angular.element(document).ready(() => {
  upgradeAdapter.bootstrap(document.body, ['myApp', 'ui.router.upgrade']);
});
```

Everything compiles without error, and I'm able to get to my angular 1 routes, but I'm now getting a navigation error when trying to get to angular2 routes (worked ok with rc3). 

Thanks!

**Comment by christopherthielen** [comment]
It's nearly ready but I haven't pushed to master or released yet.

**Comment by shane-lamb** [comment]
Great, I am also eagerly awaiting this update :)

**Comment by christopherthielen** [comment]
@rmoscowitz I've released a new `ng1-to-ng2` which is compatible with angular 2.0.0-rc.5 and ui-router 1.0.0-beta.2

Because of #13 ng1-to-ng2 can't yet be compatible with rc.6.

**Comment by rmoscowitz** [comment]
@christopherthielen Thanks a lot, it's working!
