### ISSUE TITLE
Cannot find module 'angular' on 'tsc'

### ISSUE THREAD

**Issue by 3du4** [ui-router/ng1-to-ng2#19]
when I run the 'tsc' command I get this error: 

node_modules/ui-router-ng1-to-ng2/ng1-to-ng2.d.ts(1,26): error TS2307: Cannot find module 'angular'    

typings version: 1.4.0
my typings.json file looks like this:

`{`
  `"globalDependencies": {`
    `"core-js": "registry:dt/core-js#0.0.0+20160914114559",`
    `"jasmine": "registry:dt/jasmine#2.2.0+20160621224255",`
    `"node": "registry:dt/node#6.0.0+20160928143418"`
     `}`
`}`

What is the proper way of including this library into an Angular project? I see it is constantly updated and it is now on 2.0.1. Does the typings.json matter ?

Any help would be greatly appreciated.

**Comment by 3du4** [comment]
updating typing definitions solved this issue.

**Comment by christopherthielen** [comment]
For reference:

With `typings` utility, you can use `typings install --save dt~angular`

With Typescript 2.0 and later you can simply `npm install @types/angular`
