### ISSUE TITLE
Are transition hooks supported?

### ISSUE THREAD

**Issue by trumbitta** [ui-router/ng1-to-ng2#28]
Trying to implement "Protect individual states" from https://github.com/angular-ui/ui-router/issues/2964

The transition hook function I define gets called (a trusty `console.log('QUAAACK!')` gets printed), but I'm unable to pass the expected parameters like `transition`:

```
Error: [$injector:unpr] Unknown provider: transitionProvider <- transition
http://errors.angularjs.org/1.4.8/$injector/unpr?p0=transitionProvider%20%3C-%20transition
    at :30300/vendor.js:164195:13 [<root>]
    at :30300/vendor.js:168461:20 [<root>]
    at Object.getService [as get] (vendor.js:168609) [<root>]
    at :30300/vendor.js:168466:46 [<root>]
    at getService (vendor.js:168609) [<root>]
    at Object.invoke (vendor.js:168641) [<root>]
    at decoratedNg1Hook (vendor.js:89900) [<root>]
    at :30300/vendor.js:87284:18 [<root>]
    at TransitionHook.invokeHook (vendor.js:84551) [<root>]
    at :30300/vendor.js:84204:62 [<root>]
    at processQueue (vendor.js:178919) [<root>]
    at :30300/vendor.js:178935:28 [<root>]
    at Scope.$eval (vendor.js:180179) [<root>]
    at Scope.$digest (vendor.js:179997) [<root>]
```

**Comment by trumbitta** [comment]
It started working once I tried the AngularJS version of transition hooks, that is passing `$transition$` instead of `transition`.

So:

- Hybrid AngularJS - Angular routing via `ng1-to-ng2`
- Angular state definition, with Typescript all over the place and an Angular component as the entryComponent
- *But* I must use the AngularJS version of the transition hook

Puzzling, but leaving it here in case someone else finds it useful.

**Comment by Remco75** [comment]
thnx, this is a weird one indeed! There should be a way to inject deps another way

**Comment by wawyed** [comment]
@trumbitta when running a hybrid angular application your state defininitions are actually `NgHybridStateDeclaration` not `Ng2StateDeclaration` when trying to define them in an Angular, that's what might have given you the confustion about how to define the transition hooks.

**Comment by Remco75** [comment]
hmm, thats true indeed,, thnx.
Found one other minor issue: the docs seem to be wrong:
https://github.com/ui-router/angular-hybrid#onenterexitretain states that the onEnter function should be injected like this: 
ng2StateOnEnter.$inject = [Transition, 'MyService'];

that does not work for me, it needs to me 
ng2StateOnEnter.$inject = ['$transition$', 'MyService'];

or am I missing something else @wawyed
